### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by KoljaL** [StagnantIce/sveltekit_php#1]
Hey Stagnant,

this is a nice and simple looking solution. 
But I'm not sure to understand the concept.

You catch every request in the index.php, load the backend data from php and make a window object of it.
But I guess, this will not work dynamically, so it is a a kind of static site?

Btw, there are typos in the readme, backaned 😃

**Comment by StagnantIce** [comment]
Hello, it’s working with dynamic urls also, but all pages and js using static html files and window.phpData object for data hydration. SSR working only with strings. I push example.

**Comment by StagnantIce** [comment]
see backend/blog/[slug].php

**Comment by StagnantIce** [comment]
see backend/blog/[slug].php
